baseurl = "http://hugo.spf13.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
baseURL = "http://localhost:1313/"
canonifyURLs = true



[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "en direct depuis le hugo site"
  author = "Philippe Le mong"

